## Popcorn Hack 1

In [ ]:
# CODE_RUNNER: Popcorn Hack 1
# Number of checks each search method took to find book 3 by hand
linear_checks = 1   # linear search found it on the very first check
binary_checks = 3   # binary search needed 3 checks to narrow down to it

# Show how many checks each method used
print(linear_checks)
print(binary_checks)

# Difference (linear - binary): a negative number means linear used fewer checks
print(linear_checks - binary_checks)

# Decide which method won (fewer checks wins)
if linear_checks < binary_checks:
    print("Linear search wins this time")
elif binary_checks < linear_checks:
    print("Binary search wins this time")
else:
    print("It's a tie")

## Popcorn Hack 2

In [ ]:
# CODE_RUNNER: Popcorn Hack 2

# PREDICTION (before running), worst case for n = 8 books:
#   Linear search may check every book: 8 checks
#   Binary search halves the list each check: floor(log2(8)) + 1 = 3 + 1 = 4 checks
# PREDICTION after changing n to 16:
#   Linear: 16 checks (doubles, from 8 to 16)
#   Binary: floor(log2(16)) + 1 = 4 + 1 = 5 checks (goes up by just one)

import math

# Number of books in the sorted list (must be a nonnegative whole number)
n = 16   # changed from 8 to 16

# Worst case for linear search: it inspects every item
linear_checks = n

# Worst case for binary search: floor(log2(n)) + 1 inspections
# (0 books means 0 checks, and log2(0) is undefined, so handle it separately)
binary_checks = 0 if n == 0 else math.floor(math.log2(n)) + 1

# Show the list size and the worst-case checks for each method
# (this models inspections; it does not actually search a list)
print(n)
print(linear_checks)
print(binary_checks)

## MCQ Check:

1. A
2. B
3. B
4. C

## Homework

In [1]:
# CODE_RUNNER: Homework
# PREDICTIONS (before running):
#   n = 12: books 12, visits 12, ordered pairs 12 x 12 = 144
#   n = 24: books 24, visits 24, ordered pairs 24 x 24 = 576
#   n = 0:  books 0,  visits 0,  ordered pairs 0
#   1,000 books: linear worst case 1000, binary worst case floor(log2(1000)) + 1 = 10

import math

# Report the work needed for a catalog of n books (n is a nonnegative whole number)
def catalog_report(n):
    # Visits: look at each book once, so the count grows at the same rate as n
    visits = 0
    for book in range(n):
        visits = visits + 1

    # Ordered pairs: compare every book with every book (nested loops), so n x n
    pairs = 0
    for first in range(n):
        for second in range(n):
            pairs = pairs + 1

    # Clear labels so the librarian doesn't need to know the formulas
    print(f"Books in catalog: {n}")
    print(f"Visits (look at each book once): {visits}")
    print(f"Ordered pairs (compare every book with every book): {pairs}")
    print()

# Main run: 12 books
catalog_report(12)

# Doubled catalog: 24 books
catalog_report(24)

# Empty catalog test: 0 books (the loops run zero times, so nothing crashes)
catalog_report(0)

# Checkpoint B: worst-case checks for searching 1,000 books
big_n = 1000
linear_checks = big_n
# Guard against n = 0, because log2(0) is undefined
binary_checks = 0 if big_n == 0 else math.floor(math.log2(big_n)) + 1
print(f"Linear search worst case for {big_n} books: {linear_checks} checks")
print(f"Binary search worst case for {big_n} books: {binary_checks} checks")

Books in catalog: 12
Visits (look at each book once): 12
Ordered pairs (compare every book with every book): 144

Books in catalog: 24
Visits (look at each book once): 24
Ordered pairs (compare every book with every book): 576

Books in catalog: 0
Visits (look at each book once): 0
Ordered pairs (compare every book with every book): 0

Linear search worst case for 1000 books: 1000 checks
Binary search worst case for 1000 books: 10 checks


# Tests

| Test | Input | Expected | Actual | Result |
|---|---|---|---|---|
| Main run | `n = 12` | `12`, `12`, `144` | `12`, `12`, `144` | Pass |
| Doubled catalog | `n = 24` | `24`, `24`, `576` | `24`, `24`, `576` | Pass |
| Empty catalog | `n = 0` | `0`, `0`, `0` | `0`, `0`, `0` | Pass |
| Checkpoint B | 1,000 books | linear `1000`, binary `10` | `1000`, `10` | Pass |
| Unguarded log2 | `math.log2(0)` | error | `ValueError: math domain error` | Shows the guard is needed |

Main output:

    Books in catalog: 12
    Visits (look at each book once): 12
    Ordered pairs (compare every book with every book): 144

    Books in catalog: 24
    Visits (look at each book once): 24
    Ordered pairs (compare every book with every book): 576

Empty output:

    Books in catalog: 0
    Visits (look at each book once): 0
    Ordered pairs (compare every book with every book): 0

# Growth Rates (12 → 24 books)

Visits doubled (12 → 24) because visiting each book once is linear growth:
twice the books means twice the work. Ordered pairs quadrupled (144 → 576)
because every book is paired with every book (n × n). Doubling n gives
2 × 2 = 4 times the work. This quadratic growth gets slow very quickly as
the catalog grows.

# Recommendation (1,000 books)

For repeated searches of an already sorted catalog, use **binary search**:
at most 10 checks, compared with 1,000 for linear search. That's about
100 times fewer checks per search, and the savings add up with every
repeated search.

**If the catalog is unsorted**, binary search doesn't work, because it relies
on order to throw away half the list. You would need to sort first, which
costs extra work. For a single search, plain linear search (1,000 checks)
is simpler. Sorting pays off only if you will search many times.

**If you must store an extra sorted copy**, you use twice the memory, and
both copies must stay in sync whenever books are added or removed. This
trade is worth it for a catalog searched often and changed rarely. It is
worth less for one that changes constantly.

# Design Thinking Process

**Librarian need:** The librarian needs to know how much work different
catalog tasks take as the collection grows. The librarian shouldn't have to
read formulas or code to get that answer.

**Goal:** Report the book count, the visits, and the ordered pairs for
any catalog size, including an empty one. Then recommend a search method
backed by real counts.

**Methods considered:**
- Linear search: works on any catalog, sorted or not, but the worst case
  checks every book.
- Binary search: very few checks (10 for 1,000 books), but only works on a
  sorted catalog.
- Hard-coding the answers (`print(144)`): rejected, because it breaks as soon
  as the catalog size changes.

**Prototype:** A `catalog_report(n)` function counts visits with one loop and
ordered pairs with nested loops. It is called for 12, 24, and 0 books,
followed by a checkpoint B comparison for 1,000 books.

**Actual test and revision:** I tested the binary-search formula without the
guard and got `ValueError: math domain error` from `math.log2(0)`.
**Revision:** I added `0 if n == 0 else ...` so an empty catalog returns
0 checks instead of crashing. The first draft also printed bare numbers,
like `144`, which a librarian couldn't interpret. **Revision:** I added
plain-language labels, such as "Ordered pairs (compare every book with
every book)", so the output explains itself.